//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeamTAAAU.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Wallet
    {
        public int id { get; set; }
        public int cust_id { get; set; }
        public string cupons { get; set; }
        public string giftCard { get; set; }
        public Nullable<decimal> addMoney { get; set; }
        public Nullable<decimal> spendMoney { get; set; }
    
        public virtual Customer Customer { get; set; }
    }
}
